language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install xsltproc
  - sudo apt-get install php5

script: cd build && ant check-current

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#phpunit"
    use_notice: true
